# Generated by Django 4.0.6 on 2022-07-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_csvchunk_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvchunk',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
