# Generated by Django 4.0.6 on 2022-07-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_chunk_id_csvchunk_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvchunk',
            old_name='publishing_date',
            new_name='upload_time',
        ),
    ]
