# Generated by Django 4.0.6 on 2022-08-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_publishing_date_csvchunk_upload_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvchunk',
            options={'ordering': ('-user', 'upload_time')},
        ),
    ]
